/*
 * generated by Xtext 2.10.0
 */
package org.example.helloidea.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class HelloIdeaIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new HelloIdeaStandaloneSetupIdea().createInjector
	}

}
