/*
 * generated by Xtext 2.10.0
 */
package org.example.helloidea.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class HelloIdeaIdeaModule extends AbstractHelloIdeaIdeaModule {
}
