/*
 * generated by Xtext 2.11.0
 */
package org.example.smalljava.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SmallJavaWebModule extends AbstractSmallJavaWebModule {
}
