/*
 * generated by Xtext 2.10.0
 */
package org.example.smalljava.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class SmallJavaWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public SmallJavaWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
