/*
 * generated by Xtext 2.10.0
 */
package org.example.smalljava.ui.wizard;

import org.eclipse.xtext.ui.wizard.DefaultProjectInfo;

public class SmallJavaProjectInfo extends DefaultProjectInfo {

}
