/*
 * generated by Xtext 2.10.0
 */
package org.example.customgreetings.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.example.customgreetings.greetings.Model
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GreetingsInjectorProvider)
class GreetingsParsingTest{

	@Inject
	ParseHelper<Model> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

	@Test 
	def void testCustomGreetingToString() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertEquals("Hello Xtext", result.greetings.head.toString)
	}

}
