/*
 * generated by Xtext 2.11.0
 */
package org.example.helloweb.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class HelloWebWebModule extends AbstractHelloWebWebModule {
}
