/*
 * generated by Xtext 2.10.0
 */
package org.example.xbase.expressions.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.xbase.typesystem.IBatchTypeResolver
import org.example.xbase.expressions.expressions.ExpressionsModel
import org.junit.Test
import org.junit.runner.RunWith

import static extension org.junit.Assert.*

@RunWith(XtextRunner)
@InjectWith(ExpressionsInjectorProvider)
class ExpressionsTypeComputerTest {

	@Inject extension ParseHelper<ExpressionsModel>
	@Inject IBatchTypeResolver typeResolver;

	@Test
	def void testEvalExpressionActualType() {
		'''
			val i = 0
			eval i
		'''.parse.expressions.last => [
			"java.lang.String".assertEquals(
				typeResolver.resolveTypes(it).getActualType(it).identifier
			)
		]
	}


}
