<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="school" nsURI="http://www.example.org/school" nsPrefix="school">
  <eClassifiers xsi:type="ecore:EClass" name="SchoolModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schools" upperBound="-1"
        eType="#//School" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="School" eSuperTypes="#//Named">
    <eOperations name="getStudents">
      <eGenericType eClassifier="#//Iterable">
        <eTypeArguments eClassifier="#//Student"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getTeachers">
      <eGenericType eClassifier="#//Iterable">
        <eTypeArguments eClassifier="#//Teacher"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statistics" eType="#//SchoolStatistics"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true" eSuperTypes="#//Named"/>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teachers" upperBound="-1"
        eType="#//Teacher"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Teacher" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Iterable" instanceClassName="java.lang.Iterable">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SchoolStatistics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studentsNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teachersNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studentsWithNoTeacher">
      <eGenericType eClassifier="#//Iterable">
        <eTypeArguments eClassifier="#//Student"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
