/*
 * generated by Xtext 2.10.0
 */
package org.example.helloweb


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HelloWebStandaloneSetup extends HelloWebStandaloneSetupGenerated {

	def static void doSetup() {
		new HelloWebStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
