/*
 * generated by Xtext 2.10.0
 */
package org.example.smalljava

import com.google.inject.Binder
import com.google.inject.name.Names
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy
import org.eclipse.xtext.scoping.IScopeProvider
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider
import org.example.smalljava.scoping.SmallJavaImportedNamespaceAwareLocalScopeProvider
import org.example.smalljava.scoping.SmallJavaResourceDescriptionsStrategy

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmallJavaRuntimeModule extends AbstractSmallJavaRuntimeModule {

	override void configureIScopeProviderDelegate(Binder binder) {
		binder.bind(IScopeProvider).annotatedWith(
			Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)
		).to(
			SmallJavaImportedNamespaceAwareLocalScopeProvider
		)
	}

	def Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return SmallJavaResourceDescriptionsStrategy;
	}
}
