/*
 * generated by Xtext 2.10.0
 */
package org.example.xbase.expressions


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionsStandaloneSetup extends ExpressionsStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
