/*
 * generated by Xtext 2.10.0
 */
package org.example.helloidea.idea.lang


class HelloIdeaFileType extends AbstractHelloIdeaFileType {
	public static final HelloIdeaFileType INSTANCE = new HelloIdeaFileType()
	
	new() {
		super(HelloIdeaLanguage.INSTANCE)
	}
}
