/*
 * generated by Xtext 2.9.1
 */
package org.example.entities


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EntitiesStandaloneSetup extends EntitiesStandaloneSetupGenerated {

	def static void doSetup() {
		new EntitiesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
