/*
 * generated by Xtext 2.10.0
 */
package org.example.helloidea


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HelloIdeaStandaloneSetup extends HelloIdeaStandaloneSetupGenerated {

	def static void doSetup() {
		new HelloIdeaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
