/*
 * generated by Xtext 2.10.0
 */
package org.example.helloidea.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.example.helloidea.idea.lang.HelloIdeaLanguage

class HelloIdeaCompletionContributor extends AbstractHelloIdeaCompletionContributor {
	new() {
		this(HelloIdeaLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
