/*
 * generated by Xtext 2.10.0
 */
package org.example.hellomaven


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HelloMavenStandaloneSetup extends HelloMavenStandaloneSetupGenerated {

	def static void doSetup() {
		new HelloMavenStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
