/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.example.customgreetings.ide


/**
 * Use this class to register ide components.
 */
class GreetingsIdeModule extends AbstractGreetingsIdeModule {
}
