/*
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.example.hellomaven.ide


/**
 * Use this class to register ide components.
 */
class HelloMavenIdeModule extends AbstractHelloMavenIdeModule {
}
